spring.application.name=client-manager

spring.r2dbc.url=r2dbc:mysql://localhost:3306/seek
spring.r2dbc.username=root
spring.r2dbc.password=password
spring.r2dbc.name=seek
spring.r2dbc.host=localhost
spring.r2dbc.port=3306

spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=20

spring.flyway.enabled=true
spring.flyway.url=jdbc:mysql://localhost:3306/seek
spring.flyway.user=root
spring.flyway.password=password
spring.flyway.schemas=seek
spring.flyway.locations=classpath:db/migration

adapter.jwt.secret=secret
adapter.jwt.expiration=86400000